sudo: required
language: scala
scala:
  - 2.12.0
  - 2.11.8
  - 2.10.5
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs npm
  - npm install -g kinesalite
install: bundle install
script:
  - sbt ++$TRAVIS_SCALA_VERSION --warn update compile test doc awsWrapTest/it:compile && sbt ++$TRAVIS_SCALA_VERSION awsWrapTest/it:test
